all:
    g++ -o mySerialNode  mySerialNode.cpp -std=c++11 -lrclcpp -lstd_msgs__rosidl_typesupport_cpp -lsensor_msgs__rosidl_typesupport_cpp -lrosidl_typesupport_interface -lrosidl_typesupport_cpp -lrcutils -lrmw -lrosidl_runtime_cpp -lrosidl_typesupport_introspection_cpp -lserial
